module.exports = {
  MODEL_VERSION: 'market-v4',
  STOCK_MODEL_VERSION: 'stock-v2',
  REGIME_MODEL_VERSION: 'regime-v1',
  PORT: process.env.PORT || 3001,
  CACHE_TTL: 30_000,
  CRYPTO_CACHE_TTL: 60_000,
  WATCHLIST_CACHE_TTL: 60_000,
  STALE_THRESHOLD: 5 * 60_000,
  WATCHLIST: ['TSLA', 'NVDA', 'PYPL', 'MSTR', 'HD'],
  DECISION_BANDS: {
    YES: 70,
    CAUTION: 45
  },
  CRITICAL_FEEDS: ['SPY', 'QQQ', 'VIX']
};
